package com.star.hermes.ext;

import com.star.hermes.dao.ConfigMapper;
import org.apache.ibatis.annotations.Mapper;
import tk.mybatis.mapper.common.BaseMapper;

/**
 * Description: ConfigExtDao <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:26
 */
@Mapper
public interface ConfigExtDao extends ConfigMapper, BaseMapper {

}
