package com.star.hermes.ext;

import com.star.hermes.dao.PromptMapper;
import org.apache.ibatis.annotations.Mapper;
import tk.mybatis.mapper.common.BaseMapper;

/**
 * Description: PromptExtDao <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:27
 */
@Mapper
public interface PromptExtDao extends PromptMapper, BaseMapper {

}
