package com.star.hermes.ext;

import com.star.hermes.dao.UserMapper;
import tk.mybatis.mapper.common.BaseMapper;

/**
 * Description: UserExtDao <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-8-31 18:05:28
 */
//@Mapper
public interface UserExtDao extends UserMapper, BaseMapper {

}
