package com.star.hermes.service;

import com.star.hermes.entity.Business;

import java.util.List;

/**
 * Description: BusinessService <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:24
 */
public interface BusinessService {

    /**
     * 新增
     *
     * @param business
     * @return
     */
    int save(Business business);

    /**
     * 更新操作
     *
     * @param business
     * @return
     */
    int update(Business business);

    /**
     * 物理删除操作
     *
     * @param id
     * @return
     */
    int delete(Long id);

    /**
     * 查询数量
     *
     * @param business
     * @return
     */
    int count(Business business);

    /**
     * 根据 id 查询信息
     *
     * @param id
     * @return
     */
    Business queryById(Long id);

    /**
     * 多条件查询返回集合
     *
     * @param business
     * @return
     */
    List<Business> queryList(Business business);

    /**
     * 分页多条件查询返回集合
     *
     * @param business
     * @param pageNum
     * @param countEachPage
     * @return
     */
    List<Business> queryPage(Business business, Integer pageNum, Integer countEachPage);
}
