package com.star.hermes.service;

import com.star.hermes.entity.UserPrompt;

import java.util.List;

/**
 * Description: UserPromptService <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:27
 */
public interface UserPromptService {

    /**
     * 新增
     *
     * @param userPrompt
     * @return
     */
    int save(UserPrompt userPrompt);

    /**
     * 更新操作
     *
     * @param userPrompt
     * @return
     */
    int update(UserPrompt userPrompt);

    /**
     * 物理删除操作
     *
     * @param id
     * @return
     */
    int delete(Long id);

    /**
     * 查询数量
     *
     * @param userPrompt
     * @return
     */
    int count(UserPrompt userPrompt);

    /**
     * 根据 id 查询信息
     *
     * @param id
     * @return
     */
    UserPrompt queryById(Long id);

    /**
     * 多条件查询返回集合
     *
     * @param userPrompt
     * @return
     */
    List<UserPrompt> queryList(UserPrompt userPrompt);

    /**
     * 分页多条件查询返回集合
     *
     * @param userPrompt
     * @param pageNum
     * @param countEachPage
     * @return
     */
    List<UserPrompt> queryPage(UserPrompt userPrompt, Integer pageNum, Integer countEachPage);
}
