package com.star.hermes.service;

import com.star.hermes.entity.User;

import java.util.List;

/**
 * Description: UserService <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-8-31 18:05:27
 */
public interface UserService {

    User findByEmailAndPassword(String mail, String password);

    User findByEmail(String mail);

    /**
     * 新增
     *
     * @param user
     * @return
     */
    int save(User user);

    /**
     * 更新操作
     *
     * @param user
     * @return
     */
    int update(User user);

    /**
     * 物理删除操作
     *
     * @param id
     * @return
     */
    int delete(Long id);

    /**
     * 查询数量
     *
     * @param user
     * @return
     */
    int count(User user);

    /**
     * 根据 id 查询信息
     *
     * @param id
     * @return
     */
    User queryById(Long id);

    /**
     * 多条件查询返回集合
     *
     * @param user
     * @return
     */
    List<User> queryList(User user);

    /**
     * 分页多条件查询返回集合
     *
     * @param user
     * @param pageNum
     * @param countEachPage
     * @return
     */
    List<User> queryPage(User user, Integer pageNum, Integer countEachPage);
}
