package com.star.hermes.service.impl;

import com.star.hermes.ext.BusinessExtDao;
import com.star.hermes.entity.Business;
import com.star.hermes.service.BusinessService;
import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Resource;
import java.util.List;

/**
 * Description: BusinessServiceImpl <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:24
 */
@Service
public class BusinessServiceImpl implements BusinessService {

    private static final Logger logger = LoggerFactory.getLogger(BusinessServiceImpl.class);

    @Resource
    private BusinessExtDao businessExtDao;

    @Override
    public int save(Business business) {
        return businessExtDao.insertSelective(business);
    }

    @Override
    public int update(Business business) {
        return businessExtDao.updateByPrimaryKeySelective(business);
    }

    @Override
    public int delete(Long id) {
        return businessExtDao.deleteByPrimaryKey(id);
    }

    @Override
    public int count(Business business) {
        return 0;
    }

    @Override
    public Business queryById(Long id) {
        return null;
    }

    @Override
    public List<Business> queryList(Business business) {
        return null;
    }

    @Override
    public List<Business> queryPage(Business business, Integer pageNum, Integer countEachPage) {
        return null;
    }

}
