package com.star.hermes.service.impl;

import com.star.hermes.entity.Chat;
import com.star.hermes.ext.ChatExtDao;
import com.star.hermes.service.ChatService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.List;

/**
 * Description: ChatServiceImpl <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:26
 */
@Service
public class ChatServiceImpl implements ChatService {

    private static final Logger logger = LoggerFactory.getLogger(ChatServiceImpl.class);

    @Resource
    private ChatExtDao chatExtDao;

    @Override
    public int save(Chat chat) {
        return chatExtDao.insertSelective(chat);
    }

    @Override
    public int update(Chat chat) {
        return chatExtDao.updateByPrimaryKeySelective(chat);
    }

    @Override
    public int delete(Long id) {
        return chatExtDao.deleteByPrimaryKey(id);
    }

    @Override
    public int count(Chat chat) {
        return 0;
    }

    @Override
    public Chat queryById(Long id) {
        return null;
    }

    @Override
    public List<Chat> queryList(Chat chat) {
        return null;
    }

    @Override
    public List<Chat> queryPage(Chat chat, Integer pageNum, Integer countEachPage) {
        return null;
    }

    //    @Override
    //    public int count(Chat chat){
    //        return chatExtDao.queryForCount(chat);
    //    }
    //
    //    @Override
    //    public Chat queryById(Long id) {
    //        return chatExtDao.selectByPrimaryKey(id);
    //    }
    //
    //    @Override
    //    public List<Chat> queryList(Chat chat) {
    //        return chatExtDao.queryForList(chat, null);
    //    }
    //
    //    @Override
    //    public List<Chat> queryPage(Chat chat, Integer pageNum, Integer countEachPage){
    //        return chatExtDao.queryForList(chat, PageUtil.initPage(pageNum, countEachPage));
    //    }
}
