package com.star.hermes.service.impl;

import com.star.hermes.ext.UserExtDao;
import com.star.hermes.entity.User;
import com.star.hermes.service.UserService;
import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Resource;
import java.util.List;

/**
 * Description: UserServiceImpl <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-8-31 18:05:27
 */
@Service
public class UserServiceImpl implements UserService {

    private static final Logger logger = LoggerFactory.getLogger(UserServiceImpl.class);

    @Resource
    private UserExtDao userExtDao;

    @Override
    public User findByEmailAndPassword(String mail, String password) {
        return null;
    }

    @Override
    public User findByEmail(String mail) {
        return null;
    }

    @Override
    public int save(User user) {
        return userExtDao.insertSelective(user);
    }

    @Override
    public int update(User user) {
        return userExtDao.updateByPrimaryKeySelective(user);
    }

    @Override
    public int delete(Long id) {
        return userExtDao.deleteByPrimaryKey(id);
    }

    @Override
    public int count(User user) {
        return 0;
    }

    @Override
    public User queryById(Long id) {
        return null;
    }

    @Override
    public List<User> queryList(User user) {
        return null;
    }

    @Override
    public List<User> queryPage(User user, Integer pageNum, Integer countEachPage) {
        return null;
    }

    //    @Override
    //    public int count(User user){
    //        return userExtDao.queryForCount(user);
    //    }
    //
    //    @Override
    //    public User queryById(Long id) {
    //        return userExtDao.selectByPrimaryKey(id);
    //    }
    //
    //    @Override
    //    public List<User> queryList(User user) {
    //        return userExtDao.queryForList(user, null);
    //    }
    //
    //    @Override
    //    public List<User> queryPage(User user, Integer pageNum, Integer countEachPage){
    //        return userExtDao.queryForList(user, PageUtil.initPage(pageNum, countEachPage));
    //    }
}
