package com.star.hermes.controllers;

import com.star.hermes.service.ChatService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.annotation.Resource;

/**
 * Description: ChatController <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:26
 */
@Controller
@RequestMapping("/starAI")
public class ChatController extends BaseController {
    Logger logger = LoggerFactory.getLogger(ChatController.class);

    @Resource
    private ChatService chatService;

}
