package com.star.hermes.controllers;

import com.star.hermes.common.RespCode;
import com.star.hermes.common.TcRespDto;
import com.star.hermes.service.ChatService;
import com.star.hermes.util.PwdUtil;
import org.hibernate.internal.util.StringHelper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.annotation.Resource;

/**
 * Description: ChatController <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:26
 */
@Controller
@RequestMapping("/starAI")
public class ChatController extends BaseController {
    Logger logger = LoggerFactory.getLogger(ChatController.class);

    @Resource
    private ChatService chatService;

    @RequestMapping(value = "/ask", method = RequestMethod.POST)
    public TcRespDto login(String mail, String password) {
        logger.info("login mail={}", mail);
        if (StringHelper.isBlank(mail) || StringHelper.isBlank(password)) {
            TcRespDto.fail(RespCode.INVALID_PARAM.getCode(), RespCode.INVALID_PARAM.getMsg());
        }

        String encryptPwd = PwdUtil.encrypt(password);





        return TcRespDto.success("");
    }

}
