package com.star.hermes.controllers;

import com.star.hermes.service.ConfigService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.annotation.Resource;

/**
 * Description: ConfigController <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:26
 */
@Controller
@RequestMapping("/")
public class ConfigController extends BaseController {

    @Resource
    private ConfigService configService;

}
