package com.star.hermes.controllers;

import com.star.hermes.service.PromptService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.annotation.Resource;

/**
 * Description: PromptController <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:27
 */
@Controller
@RequestMapping("/")
public class PromptController extends BaseController {

    @Resource
    private PromptService promptService;

}
