package com.star.hermes.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Description:   用户问题和回答表  ChatDto <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-10-8 16:54:26
 */
public class ChatDto implements Serializable {

    /**
     * 主键
     */
    private Integer id;

    /**
     * 用户ID
     */
    private Integer userId;

    /**
     * 对话类型
     */
    private Integer type;

    /**
     * 用户问题
     */
    private String chatQ;

    /**
     * AI回答
     */
    private String chatA;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 更新时间
     */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getChatQ() {
        return chatQ;
    }

    public void setChatQ(String chatQ) {
        this.chatQ = chatQ;
    }

    public String getChatA() {
        return chatA;
    }

    public void setChatA(String chatA) {
        this.chatA = chatA;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
