package com.star.hermes.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * Description:   用户表  UserDto <br>
 * <p>
 * Do not edit this file It was auto-generated by Code-Generator
 *
 * @since 2023-8-31 18:05:28
 */
public class UserDto implements Serializable {

    /**
     * 商业类型（0:免费 1:付费）
     */
    private Integer businessType;

    /**
     * 对话类型
     */
    private Integer count;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 主键ID
     */
    private Long id;

    /**
     * 邮箱
     */
    private String mail;

    /**
     * 用户名
     */
    private String name;

    /**
     * 更新时间
     */
    private Date updateTime;

    /**
     * 密码
     */
    private String userPassword;

    public UserDto() {
    }

    public UserDto(Integer businessType, Integer count, Date createTime, String mail, String name,
                   String userPassword) {
        this.businessType = businessType;
        this.count = count;
        this.createTime = createTime;
        this.mail = mail;
        this.name = name;
        this.userPassword = userPassword;
    }

    public Integer getBusinessType() {
        return businessType;
    }

    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getUserPassword() {
        return userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
}
